#************************** DEV root level Makefile ***********************

make	=nmake

all:
	cd country
	$(make)
	cd ..\ansi
	$(make)
	cd ..\keyboard
	$(make)
	cd ..\display
	$(make)
	cd ..\printer
	$(make)
	cd ..\driver
	$(make)
	cd ..\ramdrive
	$(make)
	cd ..\smartdrv
	$(make)
	cd ..\himem
	$(make)
	cd ..\emm386
	$(make)
	cd ..



